'use client'

import { useCallback, useEffect, useState } from 'react'
import { Plus, RefreshCw, Search } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { useTenant } from '@/components/providers/tenant-provider'
import { createDetectionRule, getDetectionRules, type DetectionRule, type DetectionRuleStatus } from '@/lib/api/detection-rules'

const statuses: DetectionRuleStatus[] = ['draft','testing','backtested','canary','approved','production','monitored','tuned','retired']
const severityClass: Record<string,string> = { critical: 'border-red-500/40 text-red-400', high: 'border-orange-500/40 text-orange-400', medium: 'border-amber-500/40 text-amber-400', low: 'border-blue-500/40 text-blue-400', info: 'border-muted text-muted-foreground' }
export default function DetectionRulesPage() {
  const { permissions } = useTenant(); const [rules,setRules]=useState<DetectionRule[]>([]); const [total,setTotal]=useState(0); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [q,setQ]=useState(''); const [showForm,setShowForm]=useState(false); const [name,setName]=useState(''); const [saving,setSaving]=useState(false)
  const canCreate = permissions.includes('detection_rules.create')
  const load = useCallback(async () => { setLoading(true); setError(null); try { const data=await getDetectionRules({q:q||undefined,limit:50,offset:0}); setRules(data.items); setTotal(data.total) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load detection rules') } finally { setLoading(false) } },[q])
  useEffect(()=>{ void load() },[load])
  async function submit(e: React.FormEvent) { e.preventDefault(); if (!name.trim()) return; setSaving(true); try { await createDetectionRule({ name, rule_type:'query', severity:'medium', version:1, enabled:true, configuration:{}, tags:[], mitre_technique_ids:[], mitre_tactic_ids:[] }); setName(''); setShowForm(false); void load() } catch(e) { setError(e instanceof Error ? e.message : 'Unable to create rule') } finally { setSaving(false) } }
  const production=rules.filter(r=>r.status==='production'&&r.enabled).length, testing=rules.filter(r=>r.status==='testing').length, disabled=rules.filter(r=>!r.enabled).length
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-balance text-xl font-semibold tracking-tight">Detection Rules</h1><p className="mt-1 text-sm text-muted-foreground">Manage, validate, and control detection logic across your security environment.</p></div>{canCreate&&<Button onClick={()=>setShowForm(true)}><Plus className="mr-2 size-4"/>Create Rule</Button>}</div>
    <div className="grid gap-4 sm:grid-cols-4">{[['Total Rules',total],['Production',production],['Testing',testing],['Disabled',disabled]].map(([label,value])=><div key={label as string} className="rounded-lg border bg-card p-4"><p className="text-xs uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</div>
    <div className="flex gap-3"><div className="relative max-w-sm flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" placeholder="Search rules" value={q} onChange={e=>setQ(e.target.value)}/></div><Button variant="outline" onClick={()=>void load()} aria-label="Refresh rules"><RefreshCw className="size-4"/></Button></div>
    {error&&<div className="rounded-lg border border-destructive/40 bg-destructive/10 p-4 text-sm text-destructive">{error}</div>}
    <div className="overflow-hidden rounded-lg border"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b bg-muted/30"><tr>{['Rule','Type','Severity','Status','Version','Enabled','Updated'].map(h=><th key={h} className="px-4 py-3 text-left font-medium text-muted-foreground">{h}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={7} className="px-4 py-12 text-center text-muted-foreground">Loading detection rules…</td></tr>:rules.map(r=><tr key={r.id} className="border-b last:border-0"><td className="px-4 py-3"><div className="font-medium">{r.name}</div><div className="max-w-xs truncate text-xs text-muted-foreground">{r.description||'No description'}</div></td><td className="px-4 py-3 capitalize">{r.rule_type}</td><td className="px-4 py-3"><Badge variant="outline" className={severityClass[r.severity]}>{r.severity}</Badge></td><td className="px-4 py-3"><Badge variant="secondary" className="capitalize">{r.status}</Badge></td><td className="px-4 py-3">v{r.version}</td><td className="px-4 py-3">{r.enabled?'Yes':'No'}</td><td className="px-4 py-3 text-muted-foreground">{new Date(r.updated_at).toLocaleDateString()}</td></tr>)}{!loading&&rules.length===0&&<tr><td colSpan={7} className="px-4 py-12 text-center text-muted-foreground">No detection rules yet. Create your first detection rule to begin building your detection library.</td></tr>}</tbody></table></div></div>
    {showForm&&<div className="fixed inset-0 z-50 grid place-items-center bg-background/80 p-4"><form onSubmit={submit} className="w-full max-w-md space-y-4 rounded-xl border bg-card p-6 shadow-xl"><h2 className="text-lg font-semibold">Create Detection Rule</h2><Input autoFocus placeholder="Rule name" value={name} onChange={e=>setName(e.target.value)} required/><p className="text-xs text-muted-foreground">New rules begin in Draft. Lifecycle promotion is controlled by the backend.</p><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={()=>setShowForm(false)}>Cancel</Button><Button disabled={saving}>{saving?'Creating…':'Create Rule'}</Button></div></form></div>}</div>
}
