"""add_role_permissions2

Revision ID: 32ce2e6cde24
Revises: f678243ad1e5
Create Date: 2026-08-04 14:21:38.736743

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa




# revision identifiers, used by Alembic.
revision: str = '32ce2e6cde24'
down_revision: Union[str, None] = 'f678243ad1e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('permissions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_tenant_role_permissions_permission_id'), 'tenant_role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_tenant_role_permissions_tenant_role_id'), 'tenant_role_permissions', ['tenant_role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_role_permissions_tenant_role_id'), table_name='tenant_role_permissions')
    op.drop_index(op.f('ix_tenant_role_permissions_permission_id'), table_name='tenant_role_permissions')
    op.drop_column('permissions', 'updated_at')
    op.drop_column('permissions', 'created_at')
    # ### end Alembic commands ###