"""update_membership_rbac_relation

Revision ID: 4ebd48c80180
Revises: 32ce2e6cde24
Create Date: 2026-08-04 14:50:36.758041

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa




# revision identifiers, used by Alembic.
revision: str = '4ebd48c80180'
down_revision: Union[str, None] = '32ce2e6cde24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('memberships_tenant_role_id_fkey'), 'memberships', type_='foreignkey')
    op.create_foreign_key(None, 'memberships', 'tenant_roles', ['tenant_role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.create_foreign_key(op.f('memberships_tenant_role_id_fkey'), 'memberships', 'tenant_roles', ['tenant_role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###