"""add security events

Revision ID: 515d231d0dc5
Revises: c4f8a1d2e9b0
Create Date: 2026-08-20 11:44:25.409766

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '515d231d0dc5'
down_revision: Union[str, None] = 'c4f8a1d2e9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=150), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('destination_ip', sa.String(length=45), nullable=True),
    sa.Column('user_identifier', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('raw_event', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_events_tenant_event_type', 'security_events', ['tenant_id', 'event_type'], unique=False)
    op.create_index('ix_security_events_tenant_severity', 'security_events', ['tenant_id', 'severity'], unique=False)
    op.create_index('ix_security_events_tenant_timestamp', 'security_events', ['tenant_id', 'timestamp'], unique=False)
    op.drop_constraint(op.f('pkce_attempts_tenant_id_fkey'), 'pkce_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'pkce_attempts', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pkce_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('pkce_attempts_tenant_id_fkey'), 'pkce_attempts', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_security_events_tenant_timestamp', table_name='security_events')
    op.drop_index('ix_security_events_tenant_severity', table_name='security_events')
    op.drop_index('ix_security_events_tenant_event_type', table_name='security_events')
    op.drop_table('security_events')
    # ### end Alembic commands ###
