"""fix pkce attempt uuid type

Revision ID: 7945f6a02600
Revises: a63b125c952d
Create Date: 2026-08-20 07:54:17.768467

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "7945f6a02600"
down_revision = "a63b125c952d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # PKCE attempts are short-lived authentication state.
    #
    # Existing attempt_id values were VARCHAR strings generated by the
    # previous implementation and cannot safely be cast to UUID.
    #
    # Since these attempts are temporary, remove the old rows before
    # changing the column type.
    op.execute(
        """
        DELETE FROM pkce_attempts
        """
    )

    op.execute(
        """
        ALTER TABLE pkce_attempts
        ALTER COLUMN attempt_id
        TYPE UUID
        USING gen_random_uuid()
        """
    )


def downgrade() -> None:
    op.execute(
        """
        ALTER TABLE pkce_attempts
        ALTER COLUMN attempt_id
        TYPE VARCHAR(128)
        USING attempt_id::text
        """
    )