"""add slug and timestamps to tenants

Revision ID: b04c5da2d9e9
Revises: 740583192cd2
Create Date: 2026-07-30 16:06:09.337986

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa




# revision identifiers, used by Alembic.
revision: str = 'b04c5da2d9e9'
down_revision: Union[str, None] = '740583192cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('tenants', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_column('tenants', 'created_at')
    op.drop_column('tenants', 'slug')
    # ### end Alembic commands ###