"""add tenant organization profile fields

Revision ID: e512b58badb6
Revises: 92c0ffb712de
Create Date: 2026-08-24 13:24:43.123385

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e512b58badb6'
down_revision: Union[str, None] = '92c0ffb712de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('industry', sa.String(length=150), nullable=True))
    op.add_column('tenants', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('plan', sa.String(length=50), server_default='Free', nullable=False))
    op.add_column('tenants', sa.Column('status', sa.String(length=50), server_default='Active', nullable=False))
    op.add_column('tenants', sa.Column('security_score', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'features')
    op.drop_column('tenants', 'security_score')
    op.drop_column('tenants', 'status')
    op.drop_column('tenants', 'plan')
    op.drop_column('tenants', 'location')
    op.drop_column('tenants', 'industry')
    op.drop_column('tenants', 'email')
    op.drop_column('tenants', 'website')
    # ### end Alembic commands ###