"""add_role_permissions

Revision ID: f678243ad1e5
Revises: 651a14c9928f
Create Date: 2026-08-04 14:07:01.069616

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f678243ad1e5'
down_revision: Union[str, None] = '651a14c9928f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('role_key', sa.String(length=100), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_key', 'permission_id')
    )
    op.create_index('ix_role_permissions_role', 'role_permissions', ['role_key'], unique=False)
    op.drop_column('permissions', 'updated_at')
    op.drop_column('permissions', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('permissions', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index('ix_role_permissions_role', table_name='role_permissions')
    op.drop_table('role_permissions')
    # ### end Alembic commands ###