"use client"

import { useMemo, useState } from "react"
import useSWR from "swr"
import { Activity, CheckCheck, ChevronLeft, ChevronRight, CircleAlert, Clock3, Radio, Search, ShieldAlert, Siren, UserRoundCheck } from "lucide-react"
import { toast } from "sonner"
import { PageHeader, Panel, SeverityBadge, StatCard, StatusBadge } from "@/components/dashboard/shared/ui"
import { getAlerts, type Alert } from "@/lib/api/alerts"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Textarea } from "@/components/ui/textarea"

type DashboardAlert = Alert & { asset: string; source: string; mitre: string; assignee: string; time: string; ioc: string }

function normalizeAlert(alert: Alert): DashboardAlert {
  const metadata = alert.metadata_json ?? {}
  return { ...alert, asset: String(metadata.asset ?? "Unassigned"), source: alert.source ?? "Detection engine", mitre: String(metadata.mitre ?? "—"), assignee: String(metadata.assignee ?? "Unassigned"), time: alert.last_seen_at, ioc: String(metadata.ioc ?? "—") }
}

export function AlertsModule() {
  const [query,setQuery]=useState(""); const [severity,setSeverity]=useState("All"); const [selected,setSelected]=useState<DashboardAlert|null>(null); const [statuses,setStatuses]=useState<Record<string,string>>({})
  const { data, error, isLoading } = useSWR("alerts", () => getAlerts({ limit: 100 }))
  const alerts = useMemo(() => (data?.items ?? []).map(normalizeAlert), [data])
  const shown=useMemo(()=>alerts.filter(a=>(severity==="All"||a.severity===severity.toLowerCase())&&`${a.title} ${a.id} ${a.asset}`.toLowerCase().includes(query.toLowerCase())),[alerts,query,severity])
  const acknowledge=(id:string)=>{setStatuses(s=>({...s,[id]:"Investigating"}));toast.success(`${id} acknowledged and audit logged`)}
  if (isLoading) return <p className="py-10 text-center text-sm text-muted-foreground">Loading tenant alerts…</p>
  if (error) return <p className="py-10 text-center text-sm text-destructive">Alert queue is unavailable.</p>
  return <div className="flex flex-col gap-6"><PageHeader eyebrow="Detection & response" title="Live alert queue" description="Triage correlated detections, collect evidence, and coordinate response across the security estate." actions={<><Button variant="outline"><Radio data-icon="inline-start"/>Live stream</Button><Button onClick={()=>toast.success("24 alerts assigned to your shift")}><UserRoundCheck data-icon="inline-start"/>Claim queue</Button></>}/>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Open alerts" value="24" change="-12%" icon={ShieldAlert} detail="6 require action"/><StatCard label="Critical" value="3" change="+1" icon={Siren} detail="Oldest: 18 minutes"/><StatCard label="Mean triage" value="6m 42s" change="-18%" icon={Clock3} detail="Inside 10m SLA"/><StatCard label="Events / min" value="18.4k" change="+8.2%" icon={Activity} detail="All collectors healthy"/></div>
    <Panel title="Detection queue" description={`${shown.length} correlated alerts in current view`} action={<span className="flex items-center gap-2 text-xs text-primary"><span className="relative flex size-2"><span className="absolute inline-flex size-full animate-ping rounded-full bg-primary opacity-60"/><span className="relative size-2 rounded-full bg-primary"/></span>Realtime</span>}>
      <div className="mb-4 flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} className="pl-9" placeholder="Search alert, asset, or identifier…"/></div><Select value={severity} onValueChange={v=>setSeverity(v??"All")}><SelectTrigger className="w-full md:w-44"><SelectValue/></SelectTrigger><SelectContent><SelectGroup>{["All","Critical","High","Medium","Low"].map(v=><SelectItem key={v} value={v}>{v} severity</SelectItem>)}</SelectGroup></SelectContent></Select><Button variant="outline" onClick={()=>{setQuery("");setSeverity("All")}}>Reset</Button></div>
      <div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Severity</TableHead><TableHead>Detection</TableHead><TableHead>Asset</TableHead><TableHead>Source / MITRE</TableHead><TableHead>Owner</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{shown.map(a=><TableRow key={a.id} className="cursor-pointer" onClick={()=>setSelected(a)}><TableCell><SeverityBadge value={a.severity}/></TableCell><TableCell><strong className="block min-w-52 text-sm">{a.title}</strong><span className="font-mono text-[11px] text-muted-foreground">{a.id} · {a.time}</span></TableCell><TableCell className="font-mono text-xs">{a.asset}</TableCell><TableCell><span className="block text-xs">{a.source}</span><span className="font-mono text-[11px] text-primary">{a.mitre}</span></TableCell><TableCell className="text-xs">{a.assignee}</TableCell><TableCell><StatusBadge value={statuses[a.id]??a.status}/></TableCell><TableCell className="text-right"><Button size="sm" variant="ghost" onClick={e=>{e.stopPropagation();acknowledge(a.id)}}><CheckCheck data-icon="inline-start"/>Ack</Button></TableCell></TableRow>)}</TableBody></Table></div>
      <div className="mt-4 flex items-center justify-between text-xs text-muted-foreground"><span>Showing 1–{shown.length} of 24 alerts</span><div className="flex gap-1"><Button size="icon-sm" variant="outline" aria-label="Previous page"><ChevronLeft/></Button><Button size="icon-sm" variant="outline" aria-label="Next page"><ChevronRight/></Button></div></div>
    </Panel>
    <Sheet open={!!selected} onOpenChange={o=>!o&&setSelected(null)}><SheetContent className="w-full overflow-y-auto sm:max-w-2xl"><SheetHeader><SheetTitle className="pr-8">{selected?.title}</SheetTitle><SheetDescription>{selected?.id} · observed {selected?.time}</SheetDescription></SheetHeader>{selected&&<div className="flex flex-col gap-5 p-4"><div className="flex flex-wrap gap-2"><SeverityBadge value={selected.severity}/><StatusBadge value={statuses[selected.id]??selected.status}/><span className="rounded-md border px-2 py-1 font-mono text-xs text-primary">MITRE {selected.mitre}</span></div><div className="grid gap-3 sm:grid-cols-3">{[["Detection source",selected.source],["Related asset",selected.asset],["Assigned to",selected.assignee]].map(([k,v])=><div key={k} className="rounded-md border bg-muted/30 p-3"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">{k}</p><p className="mt-1 text-sm">{v}</p></div>)}</div><Tabs defaultValue="timeline"><TabsList><TabsTrigger value="timeline">Timeline</TabsTrigger><TabsTrigger value="evidence">Evidence</TabsTrigger><TabsTrigger value="response">Response</TabsTrigger></TabsList><TabsContent value="timeline" className="flex flex-col gap-3 pt-4">{["Detection correlated from 18 raw events","Suspicious process tree isolated","Outbound IOC matched threat intelligence","Investigation opened by automation"].map((t,i)=><div key={t} className="flex gap-3"><span className="mt-1 size-2 rounded-full bg-primary"/><div><p className="text-sm">{t}</p><p className="font-mono text-[11px] text-muted-foreground">{i*4+2} minutes ago</p></div></div>)}</TabsContent><TabsContent value="evidence" className="pt-4"><div className="rounded-md border bg-background/50 p-4 font-mono text-xs leading-6"><span className="text-primary">IOC</span> {selected.ioc}<br/><span className="text-primary">Process</span> powershell.exe -enc JABXAGMAPQ…<br/><span className="text-primary">Parent</span> WINWORD.EXE / pid 4821<br/><span className="text-primary">Confidence</span> 96%</div></TabsContent><TabsContent value="response" className="flex flex-col gap-3 pt-4"><Button onClick={()=>acknowledge(selected.id)}><CheckCheck data-icon="inline-start"/>Acknowledge detection</Button><Button variant="outline" onClick={()=>toast.success("Asset isolation request sent")}>Isolate related asset</Button><Button variant="destructive" onClick={()=>toast.success("Alert escalated to incident commander")}><CircleAlert data-icon="inline-start"/>Escalate incident</Button></TabsContent></Tabs><div><label htmlFor="note" className="mb-2 block text-sm font-medium">Analyst note</label><Textarea id="note" placeholder="Document findings, hypothesis, and next action…"/><Button className="mt-2" variant="outline" onClick={()=>toast.success("Analyst note added")}>Add note</Button></div></div>}</SheetContent></Sheet>
  </div>
}
