export type SubscriptionTier = "Sentinel" | "Guardian" | "Fortress" | "Enterprise"
export type SubscriberStatus = "active" | "trial" | "past_due" | "churned"

export type Subscriber = {
  id: string
  company: string
  contactName: string
  email: string
  tier: SubscriptionTier
  status: SubscriberStatus
  mrr: number
  seats: number
  endpointsProtected: number
  openIncidents: number
  healthScore: number
  region: string
  joinedAt: string
  renewalAt: string
  accountManager: string
  tenantId?: string
}

export const TIERS: SubscriptionTier[] = ["Sentinel", "Guardian", "Fortress", "Enterprise"]
export const STATUSES: SubscriberStatus[] = ["active", "trial", "past_due", "churned"]

export const STATUS_LABEL: Record<SubscriberStatus, string> = {
  active: "Active",
  trial: "Trial",
  past_due: "Past Due",
  churned: "Churned",
}

export const subscribers: Subscriber[] = [
  {
    id: "SUB-1001",
    company: "Meridian Financial Group",
    contactName: "Alicia Bennett",
    email: "a.bennett@meridianfg.com",
    tier: "Enterprise",
    status: "active",
    mrr: 18500,
    seats: 240,
    endpointsProtected: 4820,
    openIncidents: 2,
    healthScore: 94,
    region: "North America",
    joinedAt: "2023-02-14",
    renewalAt: "2026-02-14",
    accountManager: "Devon Clarke",
  },
  {
    id: "SUB-1002",
    company: "Nordwind Logistics",
    contactName: "Tobias Hartmann",
    email: "t.hartmann@nordwind.eu",
    tier: "Fortress",
    status: "active",
    mrr: 9200,
    seats: 120,
    endpointsProtected: 2110,
    openIncidents: 0,
    healthScore: 88,
    region: "Europe",
    joinedAt: "2023-06-03",
    renewalAt: "2026-06-03",
    accountManager: "Priya Nair",
  },
  {
    id: "SUB-1003",
    company: "Halcyon Health Systems",
    contactName: "Dr. Renee Okafor",
    email: "r.okafor@halcyonhealth.org",
    tier: "Enterprise",
    status: "active",
    mrr: 22400,
    seats: 310,
    endpointsProtected: 6740,
    openIncidents: 5,
    healthScore: 79,
    region: "North America",
    joinedAt: "2022-11-20",
    renewalAt: "2025-11-20",
    accountManager: "Devon Clarke",
  },
  {
    id: "SUB-1004",
    company: "Bluepeak Media",
    contactName: "Marcus Vaughn",
    email: "marcus@bluepeak.tv",
    tier: "Guardian",
    status: "trial",
    mrr: 0,
    seats: 25,
    endpointsProtected: 180,
    openIncidents: 1,
    healthScore: 62,
    region: "North America",
    joinedAt: "2026-06-28",
    renewalAt: "2026-07-28",
    accountManager: "Sasha Lin",
  },
  {
    id: "SUB-1005",
    company: "Aurora Manufacturing",
    contactName: "Elena Vasquez",
    email: "e.vasquez@auroramfg.com",
    tier: "Fortress",
    status: "past_due",
    mrr: 8600,
    seats: 95,
    endpointsProtected: 1980,
    openIncidents: 3,
    healthScore: 54,
    region: "Latin America",
    joinedAt: "2023-09-11",
    renewalAt: "2026-03-11",
    accountManager: "Priya Nair",
  },
  {
    id: "SUB-1006",
    company: "Kestrel Robotics",
    contactName: "Jun Park",
    email: "jun.park@kestrelrobotics.io",
    tier: "Guardian",
    status: "active",
    mrr: 4200,
    seats: 48,
    endpointsProtected: 640,
    openIncidents: 0,
    healthScore: 91,
    region: "Asia Pacific",
    joinedAt: "2024-01-19",
    renewalAt: "2026-01-19",
    accountManager: "Sasha Lin",
  },
  {
    id: "SUB-1007",
    company: "Cedar & Vine Retail",
    contactName: "Hannah Weiss",
    email: "hannah.weiss@cedarvine.com",
    tier: "Sentinel",
    status: "active",
    mrr: 1200,
    seats: 15,
    endpointsProtected: 120,
    openIncidents: 0,
    healthScore: 85,
    region: "Europe",
    joinedAt: "2024-04-02",
    renewalAt: "2026-04-02",
    accountManager: "Sasha Lin",
  },
  {
    id: "SUB-1008",
    company: "Vertex Energy Partners",
    contactName: "Omar Haddad",
    email: "o.haddad@vertexenergy.com",
    tier: "Enterprise",
    status: "active",
    mrr: 26800,
    seats: 420,
    endpointsProtected: 9120,
    openIncidents: 7,
    healthScore: 72,
    region: "Middle East",
    joinedAt: "2022-08-05",
    renewalAt: "2025-08-05",
    accountManager: "Devon Clarke",
  },
  {
    id: "SUB-1009",
    company: "Lighthouse Legal",
    contactName: "Grace Sullivan",
    email: "g.sullivan@lighthouselegal.com",
    tier: "Guardian",
    status: "churned",
    mrr: 0,
    seats: 60,
    endpointsProtected: 0,
    openIncidents: 0,
    healthScore: 20,
    region: "North America",
    joinedAt: "2023-03-30",
    renewalAt: "2025-03-30",
    accountManager: "Priya Nair",
  },
  {
    id: "SUB-1010",
    company: "Sable Aerospace",
    contactName: "Nathan Cole",
    email: "n.cole@sableaero.com",
    tier: "Fortress",
    status: "active",
    mrr: 11400,
    seats: 140,
    endpointsProtected: 3050,
    openIncidents: 1,
    healthScore: 90,
    region: "North America",
    joinedAt: "2023-12-12",
    renewalAt: "2026-12-12",
    accountManager: "Devon Clarke",
  },
  {
    id: "SUB-1011",
    company: "Tidewater Shipping Co.",
    contactName: "Ingrid Solberg",
    email: "i.solberg@tidewater.no",
    tier: "Guardian",
    status: "trial",
    mrr: 0,
    seats: 30,
    endpointsProtected: 210,
    openIncidents: 0,
    healthScore: 68,
    region: "Europe",
    joinedAt: "2026-07-01",
    renewalAt: "2026-07-31",
    accountManager: "Priya Nair",
  },
  {
    id: "SUB-1012",
    company: "Pinnacle Insurance",
    contactName: "Carlos Mendes",
    email: "c.mendes@pinnacleins.com",
    tier: "Enterprise",
    status: "past_due",
    mrr: 19900,
    seats: 280,
    endpointsProtected: 5410,
    openIncidents: 4,
    healthScore: 58,
    region: "Latin America",
    joinedAt: "2022-05-17",
    renewalAt: "2026-05-17",
    accountManager: "Devon Clarke",
  },
  {
    id: "SUB-1013",
    company: "Quill Software",
    contactName: "Maya Rothstein",
    email: "maya@quill.dev",
    tier: "Sentinel",
    status: "active",
    mrr: 990,
    seats: 12,
    endpointsProtected: 96,
    openIncidents: 0,
    healthScore: 87,
    region: "North America",
    joinedAt: "2024-08-21",
    renewalAt: "2026-08-21",
    accountManager: "Sasha Lin",
  },
  {
    id: "SUB-1014",
    company: "Orchid Biotech",
    contactName: "Dr. Wei Zhang",
    email: "w.zhang@orchidbio.com",
    tier: "Fortress",
    status: "active",
    mrr: 10200,
    seats: 110,
    endpointsProtected: 2380,
    openIncidents: 2,
    healthScore: 83,
    region: "Asia Pacific",
    joinedAt: "2023-10-08",
    renewalAt: "2026-10-08",
    accountManager: "Priya Nair",
  },
  {
    id: "SUB-1015",
    company: "Granite Public Sector",
    contactName: "Diane Whitmore",
    email: "d.whitmore@granitegov.us",
    tier: "Enterprise",
    status: "active",
    mrr: 24100,
    seats: 360,
    endpointsProtected: 7890,
    openIncidents: 3,
    healthScore: 81,
    region: "North America",
    joinedAt: "2022-02-28",
    renewalAt: "2026-02-28",
    accountManager: "Devon Clarke",
  },
  {
    id: "SUB-1016",
    company: "Fjord Analytics",
    contactName: "Lars Eriksen",
    email: "lars@fjordanalytics.io",
    tier: "Guardian",
    status: "trial",
    mrr: 0,
    seats: 20,
    endpointsProtected: 140,
    openIncidents: 1,
    healthScore: 64,
    region: "Europe",
    joinedAt: "2026-07-05",
    renewalAt: "2026-08-04",
    accountManager: "Sasha Lin",
  },
]

export function formatCurrency(value: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(value)
}

export function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  })
}
